"""Create initial tables

Revision ID: 013c283813d8
Revises: 
Create Date: 2026-10-07 00:44:23.371073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: Union[str, None] = '013c283813d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('nsqf_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('competency_baseline', sa.JSON(), nullable=False),
    sa.Column('average_starting_salary', sa.Float(), nullable=False),
    sa.Column('min_training_cost', sa.Float(), nullable=False),
    sa.Column('max_training_cost', sa.Float(), nullable=False),
    sa.Column('training_duration_months', sa.Integer(), nullable=False),
    sa.Column('demand_index', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_code'), 'careers', ['code'], unique=True)
    op.create_index(op.f('ix_careers_sector'), 'careers', ['sector'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_user_id', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('competency_vector', sa.JSON(), nullable=True),
    sa.Column('max_family_budget', sa.Float(), nullable=False),
    sa.Column('max_duration_months', sa.Integer(), nullable=False),
    sa.Column('preferred_work_environment', sa.String(length=50), nullable=False),
    sa.Column('min_expected_salary', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_district'), 'student_profiles', ['district'], unique=False)
    op.create_index(op.f('ix_student_profiles_external_user_id'), 'student_profiles', ['external_user_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_state'), 'student_profiles', ['state'], unique=False)
    op.create_table('career_prerequisites',
    sa.Column('parent_career_id', sa.UUID(), nullable=False),
    sa.Column('child_career_id', sa.UUID(), nullable=False),
    sa.Column('transition_time_months', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['parent_career_id'], ['careers.id'], ),
    sa.PrimaryKeyConstraint('parent_career_id', 'child_career_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_prerequisites')
    op.drop_index(op.f('ix_student_profiles_state'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_external_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_district'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_careers_sector'), table_name='careers')
    op.drop_index(op.f('ix_careers_code'), table_name='careers')
    op.drop_table('careers')
    # ### end Alembic commands ###